\input texinfo  @c -*-textinfo-*-
@c %**start of header
@setfilename manual.info
@settitle Mastermind Manual
@c @firstparagraphindent insert
@c %**end of header

@copying
This manual is part of mastermind project.

Copyright @copyright{} 2015 - Dev2Space team and contributors.
Licence GPLv3
@end copying

@titlepage
@title Mastermind Manual
@subtitle Mastermind developement process description
@author Moez Bouhlel

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifplaintext
@insertcopying
@end ifplaintext

@contents

@ifnottex
@node Top
@top Welcome to Mastermind manual
This manual is part of Mastermind project. Its main focus is to give a short
presentation about Mastermind developement process.
@end ifnottex

@menu
* General Presentation::	Genaral presentation
* C Standards::			Used C Standards
* Third party libraries::	Third party libraries used on mastermind
* Developement Tools::		Tools use on developement proccess
* Index::			Index list
@end menu

@node General Presentation
@chapter Project Presentation

@cindex chapter, first
This is the first @anchor{x-chap}chapter.
@cindex index entry, another

Numbered list.
@xref{x-chap, the Cahpter}.

@enumerate
@item
first item
@item
second item
@end enumerate

@include c-standards.texi
@include third_party_libs.texi
@include dev_tools.texi

@node Index
@unnumbered Index
@printindex cp


@bye
